# Postgres on GitHub 2021-07-13 at 22:07:54

name: Test

on:
  push

jobs:
  c:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install
      run: |
        sudo apt install libpq-dev build-essential

    - name: Test
      run: |
        sudo systemctl start postgresql.service
        sudo -i -u postgres psql < load.txt
        gcc -rdynamic -Wall -I/usr/include/postgresql/ -o "select" "select.c"  -lm -lpq; ./select

  java:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Test
      run: |
        sudo systemctl start postgresql.service
        sudo  -i -u postgres psql < load.txt
        wget  -q https://jdbc.postgresql.org/download/postgresql-42.2.18.jar
        javac -d . -g -cp postgresql-42.2.18.jar Select.java && java -ea -cp .:postgresql-42.2.18.jar Select

  js:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install
      run: |
        sudo apt install nodejs
        npm install pg

    - name: Test
      run: |
        sudo systemctl start postgresql.service
        sudo -i -u postgres psql < load.txt
        nodejs select.js

  perl:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install
      run: |
        sudo cpan -T -i Data::Table::Text GitHub::Crud Digest::SHA1 Date::Manip DBI DBD::Pg

    - name: Test
      run: |
        sudo systemctl start postgresql.service
        cat load.txt
        sudo -i -u postgres psql < load.txt > output.txt
        perl select.pl
        GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} perl upload.pl

  python:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install
      run: |
        pip3 install pgdb

    - name: Test
      run: |
        sudo systemctl start postgresql.service
        cat load.txt
        sudo -i -u postgres psql < load.txt > output.txt
        python3 select.py


  Apache:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Perl
      run: |
        sudo cpan -T -i Data::Table::Text GitHub::Crud Digest::SHA1 Date::Manip CGI DBI DBD::Pg

    - name: Install Apache
      run: |
        sudo apt install apache2
        sudo a2enmod cgid
        sudo systemctl restart apache2
        curl -s http://localhost/

    - name: Start Postgre
      run: |
        sudo systemctl start postgresql.service
        sudo -i -u postgres psql < load.txt > output.txt

    - name: Install CGI
      run: |
        sudo cp selectCGI.pl /usr/lib/cgi-bin/
        sudo chmod ugo=rwx   /usr/lib/cgi-bin/selectCGI.pl
        sudo ls -la          /usr/lib/cgi-bin/selectCGI.pl
        perl                 /usr/lib/cgi-bin/selectCGI.pl

    - name: Test
      run: |
        curl -s      http://localhost/cgi-bin/selectCGI.pl

    - name: Logs
      run: |
        sudo cat /var/log/apache2/access.log
        sudo cat /var/log/apache2/error.log
